// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eulrvmjguqhnevglosjs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1bHJ2bWpndXFobmV2Z2xvc2pzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0NTYzODEsImV4cCI6MjA2MTAzMjM4MX0.86XTY8Nqkv-TIwofdbjFeFKuOqqWchyeglR22_KlmMo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);